# Generated by Django 3.1.5 on 2021-01-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(default='untitled', max_length=255),
        ),
    ]
