# Generated by Django 3.1.5 on 2021-01-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_contactmessage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
